CREATE TABLE table(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  todo TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS todos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    value TEXT NOT NULL
);

INSERT INTO todos(todo)
VALUES ("Todo 1"), ("Todo 2"), ("Todo 3")

DELETE FROM todos
WHERE id = 3

SELECT * FROM todos
SELECT todo FROM todos

DROP TABLE todos